version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: inventory-frontend-prod
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    container_name: inventory-backend-prod
    ports:
      - "5000:5000"

  postgres:
    image: postgres:16-alpine
    container_name: inventory-postgres-prod
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data: