-- =====================================================================
-- Sample / Seed Data for Inventory & Order Management System
-- Default admin password is: Admin@123  (hashed with werkzeug pbkdf2)
-- =====================================================================

-- Users (password hash generated by backend seeding script; see seed.py)
-- This .sql file is illustrative; actual seeding is performed by
-- backend/database/seed.py so password hashes are generated correctly.

INSERT INTO categories (name, description) VALUES
('Electronics', 'Electronic devices and accessories'),
('Office Supplies', 'Stationery and office equipment'),
('Furniture', 'Office and home furniture'),
('Groceries', 'Food and household consumables');

INSERT INTO products (sku, name, description, category_id, unit_price, quantity_in_stock, reorder_level) VALUES
('ELEC-001', 'Wireless Mouse', 'Ergonomic 2.4GHz wireless mouse', 1, 19.99, 150, 20),
('ELEC-002', 'USB-C Hub', '7-in-1 USB-C hub with HDMI', 1, 34.50, 80, 15),
('ELEC-003', 'Mechanical Keyboard', 'RGB backlit mechanical keyboard', 1, 59.99, 60, 10),
('OFF-001', 'A4 Paper Ream', '500 sheets, 80gsm', 2, 4.25, 500, 50),
('OFF-002', 'Ballpoint Pens (Box of 12)', 'Blue ink ballpoint pens', 2, 3.10, 300, 40),
('FUR-001', 'Ergonomic Office Chair', 'Adjustable lumbar support chair', 3, 149.00, 25, 5),
('FUR-002', 'Standing Desk', 'Electric height-adjustable desk', 3, 299.00, 15, 5),
('GRO-001', 'Coffee Beans 1kg', 'Premium arabica coffee beans', 4, 12.99, 100, 20);

INSERT INTO customers (full_name, email, phone, address) VALUES
('Acme Corp', 'purchasing@acme.example', '+1-555-0100', '123 Market St, Springfield'),
('Globex Industries', 'orders@globex.example', '+1-555-0142', '45 Industrial Ave, Metropolis'),
('Jane Doe', 'jane.doe@example.com', '+1-555-0199', '9 Maple Lane, Riverside');
